USE stock_portfolio_manager;

DROP TABLE IF EXISTS Portfolio_Stocks;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Stock_Prices;
DROP TABLE IF EXISTS Dividends;
DROP TABLE IF EXISTS Alerts;
DROP TABLE IF EXISTS Watchlist;
DROP TABLE IF EXISTS Stock_Sectors;
DROP TABLE IF EXISTS Settings;
DROP TABLE IF EXISTS Portfolios;
DROP TABLE IF EXISTS Stocks;
DROP TABLE IF EXISTS Sectors;
DROP TABLE IF EXISTS Users;
